#if !canImport(ObjectiveC)
import XCTest

extension AuthenticationControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthenticationControllerTests = [
        ("testRegister", testRegister),
        ("testRegisterFailurePasswordMismatch", testRegisterFailurePasswordMismatch),
        ("testRegisterFailureShortName", testRegisterFailureShortName),
        ("testRegisterFailureShortPassword", testRegisterFailureShortPassword),
        ("testRegisterFailureWrongEmail", testRegisterFailureWrongEmail),
    ]
}

extension EmailTokenRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EmailTokenRepositoryTests = [
        ("testCreatingEmailToken", testCreatingEmailToken),
        ("testDeleteEmailToken", testDeleteEmailToken),
        ("testFindingEmailTokenByToken", testFindingEmailTokenByToken),
        ("testFindTokenByUserId", testFindTokenByUserId),
    ]
}

extension PasswordTokenRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PasswordTokenRepositoryTests = [
        ("testCount", testCount),
        ("testCreate", testCreate),
        ("testDelete", testDelete),
        ("testDeleteFor", testDeleteFor),
        ("testFindByToken", testFindByToken),
        ("testFindByUserID", testFindByUserID),
        ("testGetter", testGetter),
    ]
}

extension RefreshTokenRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RefreshTokenRepositoryTests = [
        ("testCreatingToken", testCreatingToken),
        ("testDeleteFor", testDeleteFor),
        ("testDeletingToken", testDeletingToken),
        ("testFindingTokenById", testFindingTokenById),
        ("testFindingTokenByTokenString", testFindingTokenByTokenString),
        ("testGetCount", testGetCount),
        ("testGetter", testGetter),
    ]
}

extension UserRepositoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserRepositoryTests = [
        ("testCount", testCount),
        ("testCreatingUser", testCreatingUser),
        ("testDeletingUser", testDeletingUser),
        ("testFindByEmail", testFindByEmail),
        ("testFindUserById", testFindUserById),
        ("testGetAllUsers", testGetAllUsers),
        ("testGetter", testGetter),
        ("testSetFieldValue", testSetFieldValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AuthenticationControllerTests.__allTests__AuthenticationControllerTests),
        testCase(EmailTokenRepositoryTests.__allTests__EmailTokenRepositoryTests),
        testCase(PasswordTokenRepositoryTests.__allTests__PasswordTokenRepositoryTests),
        testCase(RefreshTokenRepositoryTests.__allTests__RefreshTokenRepositoryTests),
        testCase(UserRepositoryTests.__allTests__UserRepositoryTests),
    ]
}
#endif
